
/** @file
 * @brief
 * @details Header file that defines the signature for each MLIR/Quake pass
 * defined in the  Stack .
 *
 * @par
 * This header must be included to use the collection of cancellation passes
 * that are part of the Stack.
 */

#pragma once

#include "mlir/Pass/Pass.h"

/**
 * @def CUDAQ_PREFIX_FUNCTION
 * @brief Macro defining the prefix of each quantum kernel generated by
 * MLIR/Quake. This macro is used to identify MLIR/Quake quantum kernels.
 */
#define CUDAQ_PREFIX_FUNCTION "__nvqpp__mlirgen__"

using mlir::Pass;

namespace mqss::opt {

/// 1
std::unique_ptr<Pass> createXXToIdPass();

/// 2
std::unique_ptr<Pass> createYYToIdPass();

/// 3
std::unique_ptr<Pass> createZZToIdPass();

/// 4
std::unique_ptr<Pass> createSSdgToIdPass();

/// 5
std::unique_ptr<Pass> createSdgSToIdPass();

/// 6
std::unique_ptr<Pass> createTTdgToIdPass();

/// 7
std::unique_ptr<Pass> createTdgTToIdPass();

/// 8
std::unique_ptr<Pass> createHHToIdPass();

/// 9
std::unique_ptr<Pass> createCxCxToIdPass();

/// 10
std::unique_ptr<Pass> createCyCyToIdPass();

/// 11
std::unique_ptr<Pass> createCzCzToIdPass();

/// 12
std::unique_ptr<Pass> createZeroRxToIdPass();

/// 13
std::unique_ptr<Pass> createZeroRyToIdPass();

/// 14
std::unique_ptr<Pass> createZeroRzToIdPass();

/// 15
std::unique_ptr<Pass> createGeneralCancellationsPass();

} // namespace mqss::opt

// Declarative passes
/**
 * @def GEN_PASS_DECL
 * @brief Macro for declaring passes for registration.
 */
#define GEN_PASS_DECL
/**
 * @def GEN_PASS_REGISTRATION
 * @brief Macro for pass registration.
 */
#define GEN_PASS_REGISTRATION
// NOLINTNEXTLINE
#include "Passes/Cancellations.h.inc"