/* This code and any associated documentation is provided "as is"

Copyright 2024 Munich Quantum Software Stack Project

    Licensed under the Apache License, Version 2.0 with LLVM Exceptions (the
                                     "License"); you may not use this file
except in compliance with the License. You may obtain a copy of the License at

https://github.com/Munich-Quantum-Software-Stack/passes/blob/develop/LICENSE

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.

SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
*************************************************************************
  author Martin Letras
  date   February 2025
  version 1.0
*************************************************************************/
/** @file
 * @brief
 * @details Header file that defines the signature for each MLIR/Quake pass
 * defined in the Munich Quantum Software Stack (MQSS).
 *
 * @par
 * This header must be included to use the collection of decomposition passes
 * that are part of the MQSS.
 */

#pragma once

#include "mlir/Pass/Pass.h"

/**
 * @def CUDAQ_PREFIX_FUNCTION
 * @brief Macro defining the prefix of each quantum kernel generated by
 * MLIR/Quake. This macro is used to identify MLIR/Quake quantum kernels.
 */
#define CUDAQ_PREFIX_FUNCTION "__nvqpp__mlirgen__"

using mlir::Pass;

namespace mqss::opt {

/// 1
std::unique_ptr<Pass> createReverseCxPass();

/// 2
std::unique_ptr<Pass> createCxToLowerHCzHPass();

/// 3
std::unique_ptr<Pass> createCxToUpperHCzHPass();

/// 4
std::unique_ptr<Pass> createCzToLowerHCxHPass();

/// 5
std::unique_ptr<Pass> createCzToUpperHCxHPass();

/// 6
std::unique_ptr<Pass> createRxToHRzHPass();

/// 7
std::unique_ptr<Pass> createRzToHRxHPass();

/// 8
std::unique_ptr<Pass> createCrxToHCrzHPass();

/// 9
std::unique_ptr<Pass> createCrzToHCrxHPass();

/// 10
std::unique_ptr<Pass> createSdgToSSSPass();

/// 11
std::unique_ptr<Pass> createSToSdgSdgSdgPass();

/// 12
std::unique_ptr<Pass> createSToTTPass();

/// 13
std::unique_ptr<Pass> createXToHZHPass();

/// 14
std::unique_ptr<Pass> createZToHXHPass();

/// 15
std::unique_ptr<Pass> createSwapToLowerCxCxCxPass();

/// 16
std::unique_ptr<Pass> createSwapToUpperCxCxCxPass();
/// 17 x
std::unique_ptr<Pass> createHToRzXRzPass();
/// 18 x
std::unique_ptr<Pass> createXToRxPass();
/// 18 x
std::unique_ptr<Pass> createYToRyPass();
/// 19 x
std::unique_ptr<Pass> createZToRzPass();
/// 20 x
std::unique_ptr<Pass> createSToRzPass();
/// 21 x
std::unique_ptr<Pass> createSdgToRzPass();
/// 22 x
std::unique_ptr<Pass> createTToRzPass();
/// 23 x
std::unique_ptr<Pass> createR1ToRzPass();
/// 24
std::unique_ptr<Pass> createU2ToRzRyRzPass();
/// 25 x
std::unique_ptr<Pass> createU3ToRzRyRzPass();
/// 26 x
std::unique_ptr<Pass> createRyToRzRyRzPass();
/// 27 x
std::unique_ptr<Pass> createCyToSCxSdgPass();
/// 28 x
std::unique_ptr<Pass> createRzToU3Pass();
/// 29 x
std::unique_ptr<Pass> createCRyToRzCRxRzPass();
/// 30 x
std::unique_ptr<Pass> createCRzToRzCxRzCxPass();
/// 31 x
std::unique_ptr<Pass> createCRzToCu3Pass();





} // namespace mqss::opt

// Declarative passes
/**
 * @def GEN_PASS_DECL
 * @brief Macro for declaring passes for registration.
 */
#define GEN_PASS_DECL
/**
 * @def GEN_PASS_REGISTRATION
 * @brief Macro for pass registration.
 */
#define GEN_PASS_REGISTRATION
// NOLINTNEXTLINE
#include "Passes/Decompositions.h.inc"