
/** @file
 * @brief
 * @details Header file that defines the signature for each MLIR/Quake defined
 * into the  Stack .
 *
 * @par
 * This header must be included to use the collection of example passes that are
 * part of the Stack.
 */

#ifndef EXAMPLES_H
#define EXAMPLES_H

#pragma once

#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Pass/PassRegistry.h"

#include "llvm/Support/raw_ostream.h"

#include <stdexcept>

/**
 * @def CUDAQ_PREFIX_FUNCTION
 * @brief Macro defining the prefix of each quantum kernel generated by QUAKE
 * MLIR. This macro is used to identify MLIR/Quake quantum kernels.
 */
#define CUDAQ_PREFIX_FUNCTION "__nvqpp__mlirgen__"

namespace mqss::opt {

/**
 * @brief Example custom MLIR pass.
   @details This method constructs an mlir::Pass of the type CustomExamplePass.
 This pass operates on any given MLIR/Quake module and replaces all Hadamard
 gates into a quantum circuit by S gates.

  \image html docs/_static/mqss-passes/CustomExamplePass.png width=60%

   @return An `mlir::Pass` object containing the definition of the
 CustomExamplePass. This `mlir::Pass` object has to be passed to an
 `mlir::PassManager` to transform any given MLIR module.
 */
std::unique_ptr<mlir::Pass> createCustomExamplePass();

/**
 * @brief Example MLIR pass that traverses a given MLIR/Quake.
   @details This method constructs an `mlir::Pass` of the type
 PrintQuakeGatesPas. This pass operates on any MLIR/Quake module and visit each
 operation dumping its name and type into the parameter `ostream`.
   @param[out] ostream A raw stream object that stores information about any
 given MLIR module.
   @return An `mlir::Pass` object containing the definition of the
 PrintQuakeGatesPas. This `mlir::Pass` object has to be passed to an
 `mlir::PassManager` to take effect on any given MLIR module.
 */
std::unique_ptr<mlir::Pass>
createPrintQuakeGatesPass(llvm::raw_string_ostream &ostream);
} // namespace mqss::opt
#endif // EXAMPLES_H
